# Generated by Django 4.1.5 on 2023-02-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCorder', '0002_entregable_profesor_alter_estudiante_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
